### ISSUE TITLE
strcmp not working as expected 

### ISSUE THREAD

**Issue by falcon027** [supercamel/SpinoDB#10]
I have tested the new version and have encountered the following problem: The filtering of rows does not seem to work it always returns an empty row set if I specify a filter.  It seems to be due to the comparison method (strcmp). I have tried various things but nothing has worked. If you have any ideas on how to solve this, I would appreciate a reply.

```
    bool DomView::operator==(const DomView &other) const
    {
        if ((type == DOM_NODE_TYPE_UINT) && (other.type == DOM_NODE_TYPE_UINT))
        {
            return value.u == other.value.u;
        }
        else if ((type == DOM_NODE_TYPE_INT) && (other.type == DOM_NODE_TYPE_INT))
        {
            return value.i == other.value.i;
        }
        else if (is_numeric() && other.is_numeric())
        {
            return get_numeric_as_double() == other.get_numeric_as_double();
        }
        else if (is_string() && other.is_string())
        {
            return strcmp(get_string(), other.get_string()) == 0; // <---- This seems to not work 
        }
        return false;
    }

```

**Comment by supercamel** [comment]
Hello, 
I've built fairly comprehensive unit tests for the DomNode and DomView classes. I do not think the problem is in the DomView or DomNode classes and I'm not sure how to reproduce what you are seeing. Are you able to create some minimum code that can reproduce this issue?

**Comment by falcon027** [comment]
I investigated the problem, and maybe it is more related to the parser. The bug occurs every time an UUID is used as filter criteria. Like: {id: ”04b58b3e-21e4-4fe4-badb-44e1d0fa0eca”}. 
If one creates a record with only the first characters of the id like ‘04b58b3e-21e4-‘ it works  but as soon as the last ‘-’ is followed by a number like ‘04b58b3e-21e4-4’ the record is not found. 

04b58b3e-21e4-4fe4-badb-44e1d0fa0eca => nothing found 
04b58b3e-21e4- => is found 
04b58b3e-21e4-4 => nothing found

**Comment by supercamel** [comment]
Interesting, thanks. I can reproduce this so . . fix coming shortly.

**Comment by supercamel** [comment]
There is an optimization for short strings. A normal (long) string is a struct with a pointer (8 bytes) + a 4 byte uint to hold the size + 4 bytes padding. To save an allocation, if a string is less than 14 bytes, it gets packed into this space along with a null terminator and a single byte to hold the size. I believe this bug was caused by long strings not being null terminated properly. Documents with short strings would have been fine but long strings could not be searched properly. 
Looking forward to your feedback!

**Comment by supercamel** [comment]
Come to think of it, strings with null terminators inside them might not be searched for properly either . . .
