### ISSUE TITLE
The consolidation seems to be slower than expected 

### ISSUE THREAD

**Issue by falcon027** [supercamel/SpinoDB#7]
The consolidation seems to be slower than expected (Collection 100k records and log 160 MiB => 54s). Especially with a lot of deletes in the log. I could not find a reason for this, but maybe it has to do with the complete index rebuild after each action. If someone has an idea to speed this process up, please let me know.

**Comment by supercamel** [comment]
Unfortunately, drop is O(n) time complexity. 

dropById is O log(n) and so is findOne(). You can probably speed it up a lot by replacing 'drop' with a findOne and dropById. If you try this, please let me know how it goes.

**Comment by supercamel** [comment]
This should be fixed in the 1.2.0 release. drop is O log(n) now.
